// src/app/layout.tsx
import "./globals.css";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { SolanaProvider } from "@/components/solana/solana-provider";
import { UiLayout } from "@/components/ui/ui-layout";
import { ReactQueryProvider } from "./react-query-provider";
import { SocketInit } from "./socket_init"; 
export const metadata = {
  title: "headlined",
  description: "Generated by create-solana-dapp",
};

const links = [
  { label: "Account", path: "/account" },
  { label: "Clusters", path: "/clusters" },
  { label: "SnipeSweepers Program", path: "/snipe_sweepers" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <SocketInit /> {/* 👈 moved useEffect here */}
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
